### ISSUE TITLE
Cannot extract file

### ISSUE THREAD

**Issue by MrARM** [rawling/RIFF-Extractor#1]
I changed the file name accordingly and it still will not dump it,
im running windows 7 x64
i did this:
    Changeed the filename in the file
    ran gcc riff.c
    a.exe
Nothing happens.

**Comment by rawling** [comment]
Six years on, I've just about remembered why I wrote this, but I don't have any blinding flashes of insight.

Are you sure your input file has the RIFF byte sequence in it somewhere?

**Comment by EmulatorCentral** [comment]
Im not confident, im trying to rip a 1995 computer game

**Comment by rawling** [comment]
I'd open it with a hex editor and see if it has the byte sequence RIFF.

**Comment by rawling** [comment]
Or put some printf statements in to trace through the code.
